name: CI Pipeline - Walking Skeleton

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Lấy mã nguồn về
      uses: actions/checkout@v4
      
    - name: Cài đặt Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Cài đặt thư viện Jest
      run: npm install
      
    - name: Chạy Unit Test
      run: npm test
